apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kwnj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-kwnj@sha256:5c98b65bd675feb7c5d6d9f6d959e0900f464bd9797c49b6f9256785d93e68b2
        name: my-nodejs
        resources: {}
status: {}
